### PR TITLE
LBY - UI rework

### PR DESCRIPTION
**Pull request by Fito**

### CODE REVIEW

**Comment by Fito** [comment]
@jensvdh This is the branch referenced in https://github.com/worldofbalance/unity-game-client/issues/18

**Comment by jensvdh** [comment]
:+1: Let's try and solve the Merge Conflicts

**Comment by jensvdh** [comment]
Sweet.

So this is UI-Rework, but 0 commits behind development. Right?

**Comment by Fito** [comment]
Yes, this is up to date with development

**Pull request merged**
