### PR TITLE
LBY - Adds MiniGamesConfig script

### PR DESCRIPTION
**Pull request by Fito**
- This object allows to easily control which games are available through
  the lobby.
- The object is attached to the Local Object in the World scene.
- Developers can check or uncheck the games they whish to make
  available through the unity Editor.

### CODE REVIEW

**Comment by Fito** [comment]
@jensvdh could you please review?
This feature was requested to the lobby team by Prof. Yoon.

I decided to implement this configuration as an object with public variables so it can be easily configured through the unity editor (as opposed to opening some text file and typing in values).

**Comment by jensvdh** [comment]
Looks good to me. Although this just hides the buttons. It doesn't actually remove all the assets for certain minigames. So I'm assuming 'cut' minigames would still be part of the Android package.

**Comment by jensvdh** [comment]
@Fito feel free to merge.

**Comment by Fito** [comment]
Yes, this was a quick feature to control which games are available through the lobby.

**Pull request merged**
