### PR TITLE
LBY - added some soothing background music to the lobby scene

### PR DESCRIPTION
**Pull request by j1george**

### CODE REVIEW

**Comment by Fito** [comment]
@iamthepanda Could you resolve the merge conflicts and push another commit to this branch, so we can merge it?

**Comment by Fito** [comment]
@iamthepanda I tried merging this, but I'm not sure how to test it. I don't get any music playing when I run the lobby. I also can't find were the music was added to the world scene.

**Comment by jensvdh** [comment]
@iamthepanda Please fix the merge conflicts so we can test this.

**Comment by danamuise** [comment]
was this feature is in the task list?

**Comment by j1george** [comment]
@Fito @jensvdh attempting to merge. @danamuise paul gave the okay for this task

**Comment by j1george** [comment]
resolved the merge conflict, let me know if there is a problem.

**Pull request merged**
