### PR TITLE
SDV - Midpoint Progress Stable Version

### PR DESCRIPTION
**Pull request by ToruNagao**
Hi, this is our stable version at this point. We are really sorry it's more than 50 commits away... but please check it if the code can be merged to the development branch.

### CODE REVIEW

**Comment by rupalkhilari** [comment]
@ToruNagao i think this seems to be requesting to merge into 'dev-sdv-minigame' from 'development' 
. It should look to merge into 'development' from 'dev-sdv-minigame'

**Comment by ToruNagao** [comment]
Thanks Rupal. You are right.

For, integration team - Should I create a new pull request?

**Comment by rupalkhilari** [comment]
There seems to be some merge conflicts in this one, and i also need to make some minor changes in the connection manager before this branch can be merged and works with the development branch. Also the server jar needs to be updated before this goes out. I think we should create a new pull request once all these are taken care of.

**Comment by Fito** [comment]
@ToruNagao @rupalkhilari So are we opening a new pull request? I can also just fix the merge conflicts

**Comment by rupalkhilari** [comment]
ok, I have opened a pull request https://github.com/worldofbalance/unity-game-client/pull/72,  @anuagg will update the server jar shortly. Please let us know if you observe any issues.

**Pull request merged**
