### PR TITLE
Issue 4 - Client crashing on Windows with out-of-memory error.

### PR DESCRIPTION
**Pull request by rupalkhilari**
Modified .gitattributes to change attributes of .asset, .unity, .prefab to 'binary'.
Added sqlite3.dll, sqlite3.def for Windows users.
Issue #4

### CODE REVIEW

**Comment by jensvdh** [comment]
I'm getting a bunch of compiler errors on OSX. Did you try doing a fresh clone using this branch?

game_unity_-_wob_client_-_pc__mac___linux_standalone__personal___opengl_4_1_

**Comment by rupalkhilari** [comment]
Hmm.. Yes, I did a fresh clone of the branch. It seemed to work fine on Windows. 

```
git clone -b Issue_4_windows_out_of_memory https://github.com/worldofbalance/
unity-game-client.git
```

Does this have to do with the Editor Settings -> Asset Serialization ? I have it set to Mixed as it is [here](https://drive.google.com/file/d/0By284PnwqI5xN2FmRGZyYWpEOVU/view?usp=sharing) .

**Comment by jensvdh** [comment]
I was looking at the wrong branch. It works now. I'll merge this Pull Request. Thanks for your help/investigation! :+1:

**Comment by rupalkhilari** [comment]
Cool, thanks for testing and merging it, glad it works ok for now.

**Pull request merged**
