### PR TITLE
DEV - allow debug console to be called globally

### PR DESCRIPTION
**Pull request by j1george**
I've tested this on the Lobby and on Running Rhino and it seems to work fine for both. Basically change all your `Debug.Log` to `DebugConsole.Log` to display your debug messages on the UI instead of in your console. This has the benefit of displaying your debug messages in a more convenient place so you don't have to open up your console, and also you won't have to sift through all your other console messages to find your debug message.

### CODE REVIEW

**Comment by Fito** [comment]
@iamthepanda:
Could you undo the changes to Assets/Scripts/Config.cs, Assets/RRAssets/Scripts/Constants.cs, Assets/RRAssets/Network/NetworkResponseTable.cs 
and push again? Those changes are not related to the debug console changes, and should be on their own pull request.

**Comment by j1george** [comment]
@Fito I made the changes to the files. NetworkResponseTable.cs keeps adding the newline at the end of file for some reason. It shouldn't affect its functionality

**Comment by j1george** [comment]
@Fito Okay I reverted all the changes. NetworkResponseTable.cs was giving me errors though unless I commented out the debug message, so that might be a problem

**Comment by Fito** [comment]
👍

**Pull request merged**
