### PR TITLE
SDV - Allows two players to enter a gameroom through the lobby

### PR DESCRIPTION
**Pull request by rupalkhilari**

### CODE REVIEW

**Comment by jensvdh** [comment]
Your files have mixed tabs and spaces.

**Comment by rupalkhilari** [comment]
@jensvdh , sorry I didnt realize that would happen when copy-pasting existing code within the file, since some files use tabs. Also, since I made some unnecessary changes to the formatting in code for running rhino, I shall create a new pull request to avoid too many commits. Will keep this in mind next time.

**Comment by rupalkhilari** [comment]
Have created a new commit and pull request https://github.com/worldofbalance/unity-game-client/pull/13 . You could delete this branch if required.

**Comment by jensvdh** [comment]
Sure. I think you can just keep pushing to the same branch and it will update the pull request automatically.

**Pull request closed without merging**
